/*
Copyright 2018 The Openshift Evangelists

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	kinky_v1alpha1 "github.com/barpilot/kinky/pkg/apis/kinky/v1alpha1"
	versioned "github.com/barpilot/kinky/pkg/client/clientset/versioned"
	internalinterfaces "github.com/barpilot/kinky/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/barpilot/kinky/pkg/client/listers/kinky/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// KinkyInformer provides access to a shared informer and lister for
// Kinkies.
type KinkyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KinkyLister
}

type kinkyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKinkyInformer constructs a new informer for Kinky type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKinkyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKinkyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKinkyInformer constructs a new informer for Kinky type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKinkyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KinkyV1alpha1().Kinkies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KinkyV1alpha1().Kinkies(namespace).Watch(options)
			},
		},
		&kinky_v1alpha1.Kinky{},
		resyncPeriod,
		indexers,
	)
}

func (f *kinkyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKinkyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kinkyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kinky_v1alpha1.Kinky{}, f.defaultInformer)
}

func (f *kinkyInformer) Lister() v1alpha1.KinkyLister {
	return v1alpha1.NewKinkyLister(f.Informer().GetIndexer())
}
